name: Test Runner
on:
  workflow_dispatch: {}

jobs:
  matrixBuilder:
    name: Build version matrix
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.buildMatrix.outputs.versions }}
    steps:
      - name: Build matrix for latest patch version
        id: buildMatrix
        run: |
          # Latest patch versions as json array of strings.
          VERSIONS=`npx unity-changeset list --versions --latest-patch --json --min 2019.3`
          echo "Versions: $VERSIONS"
          echo "::set-output name=versions::$VERSIONS"

  build:
    name: ${{ matrix.unityVersion }} ${{ matrix.targetPlatform }} ${{ matrix.projectPath }} 🚀
    runs-on: ubuntu-latest
    needs: matrixBuilder
    strategy:
      fail-fast: false
      matrix:
        # projectPath:
        #   - 2018.3-legacy-render-pipeline
        #   - 2019.3-universal-render-pipeline
        #   - 2019.3-high-definition-render-pipeline
        targetPlatform:
          # - StandaloneLinux64
          # - StandaloneWindows
          # - StandaloneOSX
          # - iOS
          - Android
          # - WebGL
        unityVersion: ${{ fromJson(needs.matrixBuilder.outputs.versions) }}
#        unityVersion: [2022.3.51f1"]

    steps:
      # Workaround: https://github.com/actions/checkout/issues/165#issuecomment-657673315
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v2
        id: lib-cache
        with:
          path: test-projects/${{ matrix.projectPath }}/Library
          key: Library-Experiment-Build-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-Experiment-Build-${{ matrix.projectPath }}-${{ matrix.unityVersion }}-

      - name: Build
        id: build-1
        continue-on-error: true
        timeout-minutes: 40
        uses: game-ci/unity-builder@4e7125603b7544961022d5a1fd09094b00918abd
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: test-projects/${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}

      - name: Clean and sleep for retry
        if: steps.build-1.outcome == 'failure'
        run: |
          git add .
          git reset --hard
          sleep 120

      - name: Build (Retry)
        if: steps.build-1.outcome == 'failure'
        timeout-minutes: 40
        uses: game-ci/unity-builder@4e7125603b7544961022d5a1fd09094b00918abd
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: test-projects/${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}

      - name: Upload build artifacts
#        if: ${{ matrix.unityVersion == '2021.1.6f1' || matrix.unityVersion == '2020.1.6f1' || matrix.unityVersion == '2019.4.6f1' || matrix.unityVersion == '2019.3.6f1' || matrix.unityVersion == '2019.2.6f1' || matrix.unityVersion == '2019.1.6f1' || matrix.unityVersion == '2018.4.6f1' }}
        uses: actions/upload-artifact@v2
        with:
          name: Build (${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }})
          path: build/${{ matrix.targetPlatform }}
